- name: Create a windows dir
  hosts: tag_ssmTarget_boot_win #need to match ssm_boot variable
  gather_facts: false
  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_shell_type: powershell
    ansible_aws_ssm_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    ansible_aws_ssm_bucket_name: tools-dev-customer  #change me...match s3 var in s3.tf 
  tasks:
    - name: Import Variables 
      include_vars: 
        file: ./win_vars.yml
        name: vardata

    - name: Create the directory
      win_file:
        path: 'C:\Temp\{{vardata.testdir}}'
        state: directory